[pytest]
# Define que archivos, clases y funciones buscar
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Opciones de ejecucion: -v (detallado) y generar reporte en carpeta reports
addopts = -v --html=reports/reporte.html --self-contained-html
